version: '3.3'

services:
  computer-mag:
    image: openjdk:11
    command: sh -c "java -jar app.jar"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - DB_URL=jdbc:mariadb://mariadb:3306/pcbuilders
      - DB_USERNAME=pcbuilders
      - DB_PASSWORD=pcb1234
    networks:
      - shared-network

networks:
  shared-network:
    external: true
