version: '3.3'

services:
  pcbuilder:
    image: openjdk:11
    hostname: pcbuilder
    command: sh -c "java -jar app.jar"
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - DB_URL=jdbc:mariadb://dbhost:3306/pcbuilder
      - DB_USERNAME=dbuser
      - DB_PASSWORD=dbpass
