// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: transfers/pc_build.proto
// Protobuf Java Version: 4.28.2

package transfers;

public final class PcBuildOuterClass {
  private PcBuildOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 28,
      /* patch= */ 2,
      /* suffix= */ "",
      PcBuildOuterClass.class.getName());
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface PcBuildOrBuilder extends
      // @@protoc_insertion_point(interface_extends:transfers.PcBuild)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    java.lang.String getUuid();
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    com.google.protobuf.ByteString
        getUuidBytes();

    /**
     * <code>string displayName = 2;</code>
     * @return The displayName.
     */
    java.lang.String getDisplayName();
    /**
     * <code>string displayName = 2;</code>
     * @return The bytes for displayName.
     */
    com.google.protobuf.ByteString
        getDisplayNameBytes();

    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    java.lang.String getDescription();
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    com.google.protobuf.ByteString
        getDescriptionBytes();

    /**
     * <code>string username = 4;</code>
     * @return The username.
     */
    java.lang.String getUsername();
    /**
     * <code>string username = 4;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>repeated string cpuIds = 5;</code>
     * @return A list containing the cpuIds.
     */
    java.util.List<java.lang.String>
        getCpuIdsList();
    /**
     * <code>repeated string cpuIds = 5;</code>
     * @return The count of cpuIds.
     */
    int getCpuIdsCount();
    /**
     * <code>repeated string cpuIds = 5;</code>
     * @param index The index of the element to return.
     * @return The cpuIds at the given index.
     */
    java.lang.String getCpuIds(int index);
    /**
     * <code>repeated string cpuIds = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the cpuIds at the given index.
     */
    com.google.protobuf.ByteString
        getCpuIdsBytes(int index);

    /**
     * <code>repeated string motherboardIds = 6;</code>
     * @return A list containing the motherboardIds.
     */
    java.util.List<java.lang.String>
        getMotherboardIdsList();
    /**
     * <code>repeated string motherboardIds = 6;</code>
     * @return The count of motherboardIds.
     */
    int getMotherboardIdsCount();
    /**
     * <code>repeated string motherboardIds = 6;</code>
     * @param index The index of the element to return.
     * @return The motherboardIds at the given index.
     */
    java.lang.String getMotherboardIds(int index);
    /**
     * <code>repeated string motherboardIds = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the motherboardIds at the given index.
     */
    com.google.protobuf.ByteString
        getMotherboardIdsBytes(int index);

    /**
     * <code>repeated string storageIds = 7;</code>
     * @return A list containing the storageIds.
     */
    java.util.List<java.lang.String>
        getStorageIdsList();
    /**
     * <code>repeated string storageIds = 7;</code>
     * @return The count of storageIds.
     */
    int getStorageIdsCount();
    /**
     * <code>repeated string storageIds = 7;</code>
     * @param index The index of the element to return.
     * @return The storageIds at the given index.
     */
    java.lang.String getStorageIds(int index);
    /**
     * <code>repeated string storageIds = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the storageIds at the given index.
     */
    com.google.protobuf.ByteString
        getStorageIdsBytes(int index);

    /**
     * <code>repeated string memoryIds = 8;</code>
     * @return A list containing the memoryIds.
     */
    java.util.List<java.lang.String>
        getMemoryIdsList();
    /**
     * <code>repeated string memoryIds = 8;</code>
     * @return The count of memoryIds.
     */
    int getMemoryIdsCount();
    /**
     * <code>repeated string memoryIds = 8;</code>
     * @param index The index of the element to return.
     * @return The memoryIds at the given index.
     */
    java.lang.String getMemoryIds(int index);
    /**
     * <code>repeated string memoryIds = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the memoryIds at the given index.
     */
    com.google.protobuf.ByteString
        getMemoryIdsBytes(int index);

    /**
     * <code>repeated string videoCardIds = 9;</code>
     * @return A list containing the videoCardIds.
     */
    java.util.List<java.lang.String>
        getVideoCardIdsList();
    /**
     * <code>repeated string videoCardIds = 9;</code>
     * @return The count of videoCardIds.
     */
    int getVideoCardIdsCount();
    /**
     * <code>repeated string videoCardIds = 9;</code>
     * @param index The index of the element to return.
     * @return The videoCardIds at the given index.
     */
    java.lang.String getVideoCardIds(int index);
    /**
     * <code>repeated string videoCardIds = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the videoCardIds at the given index.
     */
    com.google.protobuf.ByteString
        getVideoCardIdsBytes(int index);

    /**
     * <code>repeated string powerSupplyIds = 10;</code>
     * @return A list containing the powerSupplyIds.
     */
    java.util.List<java.lang.String>
        getPowerSupplyIdsList();
    /**
     * <code>repeated string powerSupplyIds = 10;</code>
     * @return The count of powerSupplyIds.
     */
    int getPowerSupplyIdsCount();
    /**
     * <code>repeated string powerSupplyIds = 10;</code>
     * @param index The index of the element to return.
     * @return The powerSupplyIds at the given index.
     */
    java.lang.String getPowerSupplyIds(int index);
    /**
     * <code>repeated string powerSupplyIds = 10;</code>
     * @param index The index of the value to return.
     * @return The bytes of the powerSupplyIds at the given index.
     */
    com.google.protobuf.ByteString
        getPowerSupplyIdsBytes(int index);

    /**
     * <code>int64 creationDate = 11;</code>
     * @return The creationDate.
     */
    long getCreationDate();

    /**
     * <code>int64 lastUpdateDate = 12;</code>
     * @return The lastUpdateDate.
     */
    long getLastUpdateDate();
  }
  /**
   * Protobuf type {@code transfers.PcBuild}
   */
  public static final class PcBuild extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:transfers.PcBuild)
      PcBuildOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 28,
        /* patch= */ 2,
        /* suffix= */ "",
        PcBuild.class.getName());
    }
    // Use PcBuild.newBuilder() to construct.
    private PcBuild(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private PcBuild() {
      uuid_ = "";
      displayName_ = "";
      description_ = "";
      username_ = "";
      cpuIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      motherboardIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      storageIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      memoryIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      videoCardIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      powerSupplyIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return transfers.PcBuildOuterClass.internal_static_transfers_PcBuild_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return transfers.PcBuildOuterClass.internal_static_transfers_PcBuild_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              transfers.PcBuildOuterClass.PcBuild.class, transfers.PcBuildOuterClass.PcBuild.Builder.class);
    }

    public static final int UUID_FIELD_NUMBER = 1;
    @SuppressWarnings("serial")
    private volatile java.lang.Object uuid_ = "";
    /**
     * <code>string uuid = 1;</code>
     * @return The uuid.
     */
    @java.lang.Override
    public java.lang.String getUuid() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        uuid_ = s;
        return s;
      }
    }
    /**
     * <code>string uuid = 1;</code>
     * @return The bytes for uuid.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUuidBytes() {
      java.lang.Object ref = uuid_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        uuid_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DISPLAYNAME_FIELD_NUMBER = 2;
    @SuppressWarnings("serial")
    private volatile java.lang.Object displayName_ = "";
    /**
     * <code>string displayName = 2;</code>
     * @return The displayName.
     */
    @java.lang.Override
    public java.lang.String getDisplayName() {
      java.lang.Object ref = displayName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        displayName_ = s;
        return s;
      }
    }
    /**
     * <code>string displayName = 2;</code>
     * @return The bytes for displayName.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDisplayNameBytes() {
      java.lang.Object ref = displayName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        displayName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DESCRIPTION_FIELD_NUMBER = 3;
    @SuppressWarnings("serial")
    private volatile java.lang.Object description_ = "";
    /**
     * <code>string description = 3;</code>
     * @return The description.
     */
    @java.lang.Override
    public java.lang.String getDescription() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        description_ = s;
        return s;
      }
    }
    /**
     * <code>string description = 3;</code>
     * @return The bytes for description.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getDescriptionBytes() {
      java.lang.Object ref = description_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        description_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int USERNAME_FIELD_NUMBER = 4;
    @SuppressWarnings("serial")
    private volatile java.lang.Object username_ = "";
    /**
     * <code>string username = 4;</code>
     * @return The username.
     */
    @java.lang.Override
    public java.lang.String getUsername() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        username_ = s;
        return s;
      }
    }
    /**
     * <code>string username = 4;</code>
     * @return The bytes for username.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      java.lang.Object ref = username_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        username_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CPUIDS_FIELD_NUMBER = 5;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList cpuIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string cpuIds = 5;</code>
     * @return A list containing the cpuIds.
     */
    public com.google.protobuf.ProtocolStringList
        getCpuIdsList() {
      return cpuIds_;
    }
    /**
     * <code>repeated string cpuIds = 5;</code>
     * @return The count of cpuIds.
     */
    public int getCpuIdsCount() {
      return cpuIds_.size();
    }
    /**
     * <code>repeated string cpuIds = 5;</code>
     * @param index The index of the element to return.
     * @return The cpuIds at the given index.
     */
    public java.lang.String getCpuIds(int index) {
      return cpuIds_.get(index);
    }
    /**
     * <code>repeated string cpuIds = 5;</code>
     * @param index The index of the value to return.
     * @return The bytes of the cpuIds at the given index.
     */
    public com.google.protobuf.ByteString
        getCpuIdsBytes(int index) {
      return cpuIds_.getByteString(index);
    }

    public static final int MOTHERBOARDIDS_FIELD_NUMBER = 6;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList motherboardIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string motherboardIds = 6;</code>
     * @return A list containing the motherboardIds.
     */
    public com.google.protobuf.ProtocolStringList
        getMotherboardIdsList() {
      return motherboardIds_;
    }
    /**
     * <code>repeated string motherboardIds = 6;</code>
     * @return The count of motherboardIds.
     */
    public int getMotherboardIdsCount() {
      return motherboardIds_.size();
    }
    /**
     * <code>repeated string motherboardIds = 6;</code>
     * @param index The index of the element to return.
     * @return The motherboardIds at the given index.
     */
    public java.lang.String getMotherboardIds(int index) {
      return motherboardIds_.get(index);
    }
    /**
     * <code>repeated string motherboardIds = 6;</code>
     * @param index The index of the value to return.
     * @return The bytes of the motherboardIds at the given index.
     */
    public com.google.protobuf.ByteString
        getMotherboardIdsBytes(int index) {
      return motherboardIds_.getByteString(index);
    }

    public static final int STORAGEIDS_FIELD_NUMBER = 7;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList storageIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string storageIds = 7;</code>
     * @return A list containing the storageIds.
     */
    public com.google.protobuf.ProtocolStringList
        getStorageIdsList() {
      return storageIds_;
    }
    /**
     * <code>repeated string storageIds = 7;</code>
     * @return The count of storageIds.
     */
    public int getStorageIdsCount() {
      return storageIds_.size();
    }
    /**
     * <code>repeated string storageIds = 7;</code>
     * @param index The index of the element to return.
     * @return The storageIds at the given index.
     */
    public java.lang.String getStorageIds(int index) {
      return storageIds_.get(index);
    }
    /**
     * <code>repeated string storageIds = 7;</code>
     * @param index The index of the value to return.
     * @return The bytes of the storageIds at the given index.
     */
    public com.google.protobuf.ByteString
        getStorageIdsBytes(int index) {
      return storageIds_.getByteString(index);
    }

    public static final int MEMORYIDS_FIELD_NUMBER = 8;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList memoryIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string memoryIds = 8;</code>
     * @return A list containing the memoryIds.
     */
    public com.google.protobuf.ProtocolStringList
        getMemoryIdsList() {
      return memoryIds_;
    }
    /**
     * <code>repeated string memoryIds = 8;</code>
     * @return The count of memoryIds.
     */
    public int getMemoryIdsCount() {
      return memoryIds_.size();
    }
    /**
     * <code>repeated string memoryIds = 8;</code>
     * @param index The index of the element to return.
     * @return The memoryIds at the given index.
     */
    public java.lang.String getMemoryIds(int index) {
      return memoryIds_.get(index);
    }
    /**
     * <code>repeated string memoryIds = 8;</code>
     * @param index The index of the value to return.
     * @return The bytes of the memoryIds at the given index.
     */
    public com.google.protobuf.ByteString
        getMemoryIdsBytes(int index) {
      return memoryIds_.getByteString(index);
    }

    public static final int VIDEOCARDIDS_FIELD_NUMBER = 9;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList videoCardIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string videoCardIds = 9;</code>
     * @return A list containing the videoCardIds.
     */
    public com.google.protobuf.ProtocolStringList
        getVideoCardIdsList() {
      return videoCardIds_;
    }
    /**
     * <code>repeated string videoCardIds = 9;</code>
     * @return The count of videoCardIds.
     */
    public int getVideoCardIdsCount() {
      return videoCardIds_.size();
    }
    /**
     * <code>repeated string videoCardIds = 9;</code>
     * @param index The index of the element to return.
     * @return The videoCardIds at the given index.
     */
    public java.lang.String getVideoCardIds(int index) {
      return videoCardIds_.get(index);
    }
    /**
     * <code>repeated string videoCardIds = 9;</code>
     * @param index The index of the value to return.
     * @return The bytes of the videoCardIds at the given index.
     */
    public com.google.protobuf.ByteString
        getVideoCardIdsBytes(int index) {
      return videoCardIds_.getByteString(index);
    }

    public static final int POWERSUPPLYIDS_FIELD_NUMBER = 10;
    @SuppressWarnings("serial")
    private com.google.protobuf.LazyStringArrayList powerSupplyIds_ =
        com.google.protobuf.LazyStringArrayList.emptyList();
    /**
     * <code>repeated string powerSupplyIds = 10;</code>
     * @return A list containing the powerSupplyIds.
     */
    public com.google.protobuf.ProtocolStringList
        getPowerSupplyIdsList() {
      return powerSupplyIds_;
    }
    /**
     * <code>repeated string powerSupplyIds = 10;</code>
     * @return The count of powerSupplyIds.
     */
    public int getPowerSupplyIdsCount() {
      return powerSupplyIds_.size();
    }
    /**
     * <code>repeated string powerSupplyIds = 10;</code>
     * @param index The index of the element to return.
     * @return The powerSupplyIds at the given index.
     */
    public java.lang.String getPowerSupplyIds(int index) {
      return powerSupplyIds_.get(index);
    }
    /**
     * <code>repeated string powerSupplyIds = 10;</code>
     * @param index The index of the value to return.
     * @return The bytes of the powerSupplyIds at the given index.
     */
    public com.google.protobuf.ByteString
        getPowerSupplyIdsBytes(int index) {
      return powerSupplyIds_.getByteString(index);
    }

    public static final int CREATIONDATE_FIELD_NUMBER = 11;
    private long creationDate_ = 0L;
    /**
     * <code>int64 creationDate = 11;</code>
     * @return The creationDate.
     */
    @java.lang.Override
    public long getCreationDate() {
      return creationDate_;
    }

    public static final int LASTUPDATEDATE_FIELD_NUMBER = 12;
    private long lastUpdateDate_ = 0L;
    /**
     * <code>int64 lastUpdateDate = 12;</code>
     * @return The lastUpdateDate.
     */
    @java.lang.Override
    public long getLastUpdateDate() {
      return lastUpdateDate_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, uuid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(displayName_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 2, displayName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 3, description_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 4, username_);
      }
      for (int i = 0; i < cpuIds_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 5, cpuIds_.getRaw(i));
      }
      for (int i = 0; i < motherboardIds_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 6, motherboardIds_.getRaw(i));
      }
      for (int i = 0; i < storageIds_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 7, storageIds_.getRaw(i));
      }
      for (int i = 0; i < memoryIds_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 8, memoryIds_.getRaw(i));
      }
      for (int i = 0; i < videoCardIds_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 9, videoCardIds_.getRaw(i));
      }
      for (int i = 0; i < powerSupplyIds_.size(); i++) {
        com.google.protobuf.GeneratedMessage.writeString(output, 10, powerSupplyIds_.getRaw(i));
      }
      if (creationDate_ != 0L) {
        output.writeInt64(11, creationDate_);
      }
      if (lastUpdateDate_ != 0L) {
        output.writeInt64(12, lastUpdateDate_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(uuid_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, uuid_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(displayName_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(2, displayName_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(description_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(3, description_);
      }
      if (!com.google.protobuf.GeneratedMessage.isStringEmpty(username_)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(4, username_);
      }
      {
        int dataSize = 0;
        for (int i = 0; i < cpuIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(cpuIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getCpuIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < motherboardIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(motherboardIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMotherboardIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < storageIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(storageIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getStorageIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < memoryIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(memoryIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getMemoryIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < videoCardIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(videoCardIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getVideoCardIdsList().size();
      }
      {
        int dataSize = 0;
        for (int i = 0; i < powerSupplyIds_.size(); i++) {
          dataSize += computeStringSizeNoTag(powerSupplyIds_.getRaw(i));
        }
        size += dataSize;
        size += 1 * getPowerSupplyIdsList().size();
      }
      if (creationDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(11, creationDate_);
      }
      if (lastUpdateDate_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(12, lastUpdateDate_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof transfers.PcBuildOuterClass.PcBuild)) {
        return super.equals(obj);
      }
      transfers.PcBuildOuterClass.PcBuild other = (transfers.PcBuildOuterClass.PcBuild) obj;

      if (!getUuid()
          .equals(other.getUuid())) return false;
      if (!getDisplayName()
          .equals(other.getDisplayName())) return false;
      if (!getDescription()
          .equals(other.getDescription())) return false;
      if (!getUsername()
          .equals(other.getUsername())) return false;
      if (!getCpuIdsList()
          .equals(other.getCpuIdsList())) return false;
      if (!getMotherboardIdsList()
          .equals(other.getMotherboardIdsList())) return false;
      if (!getStorageIdsList()
          .equals(other.getStorageIdsList())) return false;
      if (!getMemoryIdsList()
          .equals(other.getMemoryIdsList())) return false;
      if (!getVideoCardIdsList()
          .equals(other.getVideoCardIdsList())) return false;
      if (!getPowerSupplyIdsList()
          .equals(other.getPowerSupplyIdsList())) return false;
      if (getCreationDate()
          != other.getCreationDate()) return false;
      if (getLastUpdateDate()
          != other.getLastUpdateDate()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + UUID_FIELD_NUMBER;
      hash = (53 * hash) + getUuid().hashCode();
      hash = (37 * hash) + DISPLAYNAME_FIELD_NUMBER;
      hash = (53 * hash) + getDisplayName().hashCode();
      hash = (37 * hash) + DESCRIPTION_FIELD_NUMBER;
      hash = (53 * hash) + getDescription().hashCode();
      hash = (37 * hash) + USERNAME_FIELD_NUMBER;
      hash = (53 * hash) + getUsername().hashCode();
      if (getCpuIdsCount() > 0) {
        hash = (37 * hash) + CPUIDS_FIELD_NUMBER;
        hash = (53 * hash) + getCpuIdsList().hashCode();
      }
      if (getMotherboardIdsCount() > 0) {
        hash = (37 * hash) + MOTHERBOARDIDS_FIELD_NUMBER;
        hash = (53 * hash) + getMotherboardIdsList().hashCode();
      }
      if (getStorageIdsCount() > 0) {
        hash = (37 * hash) + STORAGEIDS_FIELD_NUMBER;
        hash = (53 * hash) + getStorageIdsList().hashCode();
      }
      if (getMemoryIdsCount() > 0) {
        hash = (37 * hash) + MEMORYIDS_FIELD_NUMBER;
        hash = (53 * hash) + getMemoryIdsList().hashCode();
      }
      if (getVideoCardIdsCount() > 0) {
        hash = (37 * hash) + VIDEOCARDIDS_FIELD_NUMBER;
        hash = (53 * hash) + getVideoCardIdsList().hashCode();
      }
      if (getPowerSupplyIdsCount() > 0) {
        hash = (37 * hash) + POWERSUPPLYIDS_FIELD_NUMBER;
        hash = (53 * hash) + getPowerSupplyIdsList().hashCode();
      }
      hash = (37 * hash) + CREATIONDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getCreationDate());
      hash = (37 * hash) + LASTUPDATEDATE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getLastUpdateDate());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static transfers.PcBuildOuterClass.PcBuild parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static transfers.PcBuildOuterClass.PcBuild parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static transfers.PcBuildOuterClass.PcBuild parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static transfers.PcBuildOuterClass.PcBuild parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static transfers.PcBuildOuterClass.PcBuild parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static transfers.PcBuildOuterClass.PcBuild parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static transfers.PcBuildOuterClass.PcBuild parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static transfers.PcBuildOuterClass.PcBuild parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static transfers.PcBuildOuterClass.PcBuild parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static transfers.PcBuildOuterClass.PcBuild parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static transfers.PcBuildOuterClass.PcBuild parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static transfers.PcBuildOuterClass.PcBuild parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(transfers.PcBuildOuterClass.PcBuild prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code transfers.PcBuild}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:transfers.PcBuild)
        transfers.PcBuildOuterClass.PcBuildOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return transfers.PcBuildOuterClass.internal_static_transfers_PcBuild_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return transfers.PcBuildOuterClass.internal_static_transfers_PcBuild_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                transfers.PcBuildOuterClass.PcBuild.class, transfers.PcBuildOuterClass.PcBuild.Builder.class);
      }

      // Construct using transfers.PcBuildOuterClass.PcBuild.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        uuid_ = "";
        displayName_ = "";
        description_ = "";
        username_ = "";
        cpuIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        motherboardIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        storageIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        memoryIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        videoCardIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        powerSupplyIds_ =
            com.google.protobuf.LazyStringArrayList.emptyList();
        creationDate_ = 0L;
        lastUpdateDate_ = 0L;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return transfers.PcBuildOuterClass.internal_static_transfers_PcBuild_descriptor;
      }

      @java.lang.Override
      public transfers.PcBuildOuterClass.PcBuild getDefaultInstanceForType() {
        return transfers.PcBuildOuterClass.PcBuild.getDefaultInstance();
      }

      @java.lang.Override
      public transfers.PcBuildOuterClass.PcBuild build() {
        transfers.PcBuildOuterClass.PcBuild result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public transfers.PcBuildOuterClass.PcBuild buildPartial() {
        transfers.PcBuildOuterClass.PcBuild result = new transfers.PcBuildOuterClass.PcBuild(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(transfers.PcBuildOuterClass.PcBuild result) {
        int from_bitField0_ = bitField0_;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.uuid_ = uuid_;
        }
        if (((from_bitField0_ & 0x00000002) != 0)) {
          result.displayName_ = displayName_;
        }
        if (((from_bitField0_ & 0x00000004) != 0)) {
          result.description_ = description_;
        }
        if (((from_bitField0_ & 0x00000008) != 0)) {
          result.username_ = username_;
        }
        if (((from_bitField0_ & 0x00000010) != 0)) {
          cpuIds_.makeImmutable();
          result.cpuIds_ = cpuIds_;
        }
        if (((from_bitField0_ & 0x00000020) != 0)) {
          motherboardIds_.makeImmutable();
          result.motherboardIds_ = motherboardIds_;
        }
        if (((from_bitField0_ & 0x00000040) != 0)) {
          storageIds_.makeImmutable();
          result.storageIds_ = storageIds_;
        }
        if (((from_bitField0_ & 0x00000080) != 0)) {
          memoryIds_.makeImmutable();
          result.memoryIds_ = memoryIds_;
        }
        if (((from_bitField0_ & 0x00000100) != 0)) {
          videoCardIds_.makeImmutable();
          result.videoCardIds_ = videoCardIds_;
        }
        if (((from_bitField0_ & 0x00000200) != 0)) {
          powerSupplyIds_.makeImmutable();
          result.powerSupplyIds_ = powerSupplyIds_;
        }
        if (((from_bitField0_ & 0x00000400) != 0)) {
          result.creationDate_ = creationDate_;
        }
        if (((from_bitField0_ & 0x00000800) != 0)) {
          result.lastUpdateDate_ = lastUpdateDate_;
        }
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof transfers.PcBuildOuterClass.PcBuild) {
          return mergeFrom((transfers.PcBuildOuterClass.PcBuild)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(transfers.PcBuildOuterClass.PcBuild other) {
        if (other == transfers.PcBuildOuterClass.PcBuild.getDefaultInstance()) return this;
        if (!other.getUuid().isEmpty()) {
          uuid_ = other.uuid_;
          bitField0_ |= 0x00000001;
          onChanged();
        }
        if (!other.getDisplayName().isEmpty()) {
          displayName_ = other.displayName_;
          bitField0_ |= 0x00000002;
          onChanged();
        }
        if (!other.getDescription().isEmpty()) {
          description_ = other.description_;
          bitField0_ |= 0x00000004;
          onChanged();
        }
        if (!other.getUsername().isEmpty()) {
          username_ = other.username_;
          bitField0_ |= 0x00000008;
          onChanged();
        }
        if (!other.cpuIds_.isEmpty()) {
          if (cpuIds_.isEmpty()) {
            cpuIds_ = other.cpuIds_;
            bitField0_ |= 0x00000010;
          } else {
            ensureCpuIdsIsMutable();
            cpuIds_.addAll(other.cpuIds_);
          }
          onChanged();
        }
        if (!other.motherboardIds_.isEmpty()) {
          if (motherboardIds_.isEmpty()) {
            motherboardIds_ = other.motherboardIds_;
            bitField0_ |= 0x00000020;
          } else {
            ensureMotherboardIdsIsMutable();
            motherboardIds_.addAll(other.motherboardIds_);
          }
          onChanged();
        }
        if (!other.storageIds_.isEmpty()) {
          if (storageIds_.isEmpty()) {
            storageIds_ = other.storageIds_;
            bitField0_ |= 0x00000040;
          } else {
            ensureStorageIdsIsMutable();
            storageIds_.addAll(other.storageIds_);
          }
          onChanged();
        }
        if (!other.memoryIds_.isEmpty()) {
          if (memoryIds_.isEmpty()) {
            memoryIds_ = other.memoryIds_;
            bitField0_ |= 0x00000080;
          } else {
            ensureMemoryIdsIsMutable();
            memoryIds_.addAll(other.memoryIds_);
          }
          onChanged();
        }
        if (!other.videoCardIds_.isEmpty()) {
          if (videoCardIds_.isEmpty()) {
            videoCardIds_ = other.videoCardIds_;
            bitField0_ |= 0x00000100;
          } else {
            ensureVideoCardIdsIsMutable();
            videoCardIds_.addAll(other.videoCardIds_);
          }
          onChanged();
        }
        if (!other.powerSupplyIds_.isEmpty()) {
          if (powerSupplyIds_.isEmpty()) {
            powerSupplyIds_ = other.powerSupplyIds_;
            bitField0_ |= 0x00000200;
          } else {
            ensurePowerSupplyIdsIsMutable();
            powerSupplyIds_.addAll(other.powerSupplyIds_);
          }
          onChanged();
        }
        if (other.getCreationDate() != 0L) {
          setCreationDate(other.getCreationDate());
        }
        if (other.getLastUpdateDate() != 0L) {
          setLastUpdateDate(other.getLastUpdateDate());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                uuid_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000001;
                break;
              } // case 10
              case 18: {
                displayName_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000002;
                break;
              } // case 18
              case 26: {
                description_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000004;
                break;
              } // case 26
              case 34: {
                username_ = input.readStringRequireUtf8();
                bitField0_ |= 0x00000008;
                break;
              } // case 34
              case 42: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureCpuIdsIsMutable();
                cpuIds_.add(s);
                break;
              } // case 42
              case 50: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureMotherboardIdsIsMutable();
                motherboardIds_.add(s);
                break;
              } // case 50
              case 58: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureStorageIdsIsMutable();
                storageIds_.add(s);
                break;
              } // case 58
              case 66: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureMemoryIdsIsMutable();
                memoryIds_.add(s);
                break;
              } // case 66
              case 74: {
                java.lang.String s = input.readStringRequireUtf8();
                ensureVideoCardIdsIsMutable();
                videoCardIds_.add(s);
                break;
              } // case 74
              case 82: {
                java.lang.String s = input.readStringRequireUtf8();
                ensurePowerSupplyIdsIsMutable();
                powerSupplyIds_.add(s);
                break;
              } // case 82
              case 88: {
                creationDate_ = input.readInt64();
                bitField0_ |= 0x00000400;
                break;
              } // case 88
              case 96: {
                lastUpdateDate_ = input.readInt64();
                bitField0_ |= 0x00000800;
                break;
              } // case 96
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private java.lang.Object uuid_ = "";
      /**
       * <code>string uuid = 1;</code>
       * @return The uuid.
       */
      public java.lang.String getUuid() {
        java.lang.Object ref = uuid_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          uuid_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @return The bytes for uuid.
       */
      public com.google.protobuf.ByteString
          getUuidBytes() {
        java.lang.Object ref = uuid_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uuid_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuid(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        uuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUuid() {
        uuid_ = getDefaultInstance().getUuid();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>string uuid = 1;</code>
       * @param value The bytes for uuid to set.
       * @return This builder for chaining.
       */
      public Builder setUuidBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        uuid_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }

      private java.lang.Object displayName_ = "";
      /**
       * <code>string displayName = 2;</code>
       * @return The displayName.
       */
      public java.lang.String getDisplayName() {
        java.lang.Object ref = displayName_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          displayName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string displayName = 2;</code>
       * @return The bytes for displayName.
       */
      public com.google.protobuf.ByteString
          getDisplayNameBytes() {
        java.lang.Object ref = displayName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          displayName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string displayName = 2;</code>
       * @param value The displayName to set.
       * @return This builder for chaining.
       */
      public Builder setDisplayName(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        displayName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }
      /**
       * <code>string displayName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearDisplayName() {
        displayName_ = getDefaultInstance().getDisplayName();
        bitField0_ = (bitField0_ & ~0x00000002);
        onChanged();
        return this;
      }
      /**
       * <code>string displayName = 2;</code>
       * @param value The bytes for displayName to set.
       * @return This builder for chaining.
       */
      public Builder setDisplayNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        displayName_ = value;
        bitField0_ |= 0x00000002;
        onChanged();
        return this;
      }

      private java.lang.Object description_ = "";
      /**
       * <code>string description = 3;</code>
       * @return The description.
       */
      public java.lang.String getDescription() {
        java.lang.Object ref = description_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          description_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @return The bytes for description.
       */
      public com.google.protobuf.ByteString
          getDescriptionBytes() {
        java.lang.Object ref = description_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          description_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string description = 3;</code>
       * @param value The description to set.
       * @return This builder for chaining.
       */
      public Builder setDescription(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDescription() {
        description_ = getDefaultInstance().getDescription();
        bitField0_ = (bitField0_ & ~0x00000004);
        onChanged();
        return this;
      }
      /**
       * <code>string description = 3;</code>
       * @param value The bytes for description to set.
       * @return This builder for chaining.
       */
      public Builder setDescriptionBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        description_ = value;
        bitField0_ |= 0x00000004;
        onChanged();
        return this;
      }

      private java.lang.Object username_ = "";
      /**
       * <code>string username = 4;</code>
       * @return The username.
       */
      public java.lang.String getUsername() {
        java.lang.Object ref = username_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          username_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string username = 4;</code>
       * @return The bytes for username.
       */
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        java.lang.Object ref = username_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          username_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string username = 4;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        username_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }
      /**
       * <code>string username = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        username_ = getDefaultInstance().getUsername();
        bitField0_ = (bitField0_ & ~0x00000008);
        onChanged();
        return this;
      }
      /**
       * <code>string username = 4;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        username_ = value;
        bitField0_ |= 0x00000008;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList cpuIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureCpuIdsIsMutable() {
        if (!cpuIds_.isModifiable()) {
          cpuIds_ = new com.google.protobuf.LazyStringArrayList(cpuIds_);
        }
        bitField0_ |= 0x00000010;
      }
      /**
       * <code>repeated string cpuIds = 5;</code>
       * @return A list containing the cpuIds.
       */
      public com.google.protobuf.ProtocolStringList
          getCpuIdsList() {
        cpuIds_.makeImmutable();
        return cpuIds_;
      }
      /**
       * <code>repeated string cpuIds = 5;</code>
       * @return The count of cpuIds.
       */
      public int getCpuIdsCount() {
        return cpuIds_.size();
      }
      /**
       * <code>repeated string cpuIds = 5;</code>
       * @param index The index of the element to return.
       * @return The cpuIds at the given index.
       */
      public java.lang.String getCpuIds(int index) {
        return cpuIds_.get(index);
      }
      /**
       * <code>repeated string cpuIds = 5;</code>
       * @param index The index of the value to return.
       * @return The bytes of the cpuIds at the given index.
       */
      public com.google.protobuf.ByteString
          getCpuIdsBytes(int index) {
        return cpuIds_.getByteString(index);
      }
      /**
       * <code>repeated string cpuIds = 5;</code>
       * @param index The index to set the value at.
       * @param value The cpuIds to set.
       * @return This builder for chaining.
       */
      public Builder setCpuIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCpuIdsIsMutable();
        cpuIds_.set(index, value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cpuIds = 5;</code>
       * @param value The cpuIds to add.
       * @return This builder for chaining.
       */
      public Builder addCpuIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureCpuIdsIsMutable();
        cpuIds_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cpuIds = 5;</code>
       * @param values The cpuIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllCpuIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureCpuIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, cpuIds_);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cpuIds = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearCpuIds() {
        cpuIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000010);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string cpuIds = 5;</code>
       * @param value The bytes of the cpuIds to add.
       * @return This builder for chaining.
       */
      public Builder addCpuIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureCpuIdsIsMutable();
        cpuIds_.add(value);
        bitField0_ |= 0x00000010;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList motherboardIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureMotherboardIdsIsMutable() {
        if (!motherboardIds_.isModifiable()) {
          motherboardIds_ = new com.google.protobuf.LazyStringArrayList(motherboardIds_);
        }
        bitField0_ |= 0x00000020;
      }
      /**
       * <code>repeated string motherboardIds = 6;</code>
       * @return A list containing the motherboardIds.
       */
      public com.google.protobuf.ProtocolStringList
          getMotherboardIdsList() {
        motherboardIds_.makeImmutable();
        return motherboardIds_;
      }
      /**
       * <code>repeated string motherboardIds = 6;</code>
       * @return The count of motherboardIds.
       */
      public int getMotherboardIdsCount() {
        return motherboardIds_.size();
      }
      /**
       * <code>repeated string motherboardIds = 6;</code>
       * @param index The index of the element to return.
       * @return The motherboardIds at the given index.
       */
      public java.lang.String getMotherboardIds(int index) {
        return motherboardIds_.get(index);
      }
      /**
       * <code>repeated string motherboardIds = 6;</code>
       * @param index The index of the value to return.
       * @return The bytes of the motherboardIds at the given index.
       */
      public com.google.protobuf.ByteString
          getMotherboardIdsBytes(int index) {
        return motherboardIds_.getByteString(index);
      }
      /**
       * <code>repeated string motherboardIds = 6;</code>
       * @param index The index to set the value at.
       * @param value The motherboardIds to set.
       * @return This builder for chaining.
       */
      public Builder setMotherboardIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureMotherboardIdsIsMutable();
        motherboardIds_.set(index, value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string motherboardIds = 6;</code>
       * @param value The motherboardIds to add.
       * @return This builder for chaining.
       */
      public Builder addMotherboardIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureMotherboardIdsIsMutable();
        motherboardIds_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string motherboardIds = 6;</code>
       * @param values The motherboardIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllMotherboardIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureMotherboardIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, motherboardIds_);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string motherboardIds = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearMotherboardIds() {
        motherboardIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000020);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string motherboardIds = 6;</code>
       * @param value The bytes of the motherboardIds to add.
       * @return This builder for chaining.
       */
      public Builder addMotherboardIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureMotherboardIdsIsMutable();
        motherboardIds_.add(value);
        bitField0_ |= 0x00000020;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList storageIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureStorageIdsIsMutable() {
        if (!storageIds_.isModifiable()) {
          storageIds_ = new com.google.protobuf.LazyStringArrayList(storageIds_);
        }
        bitField0_ |= 0x00000040;
      }
      /**
       * <code>repeated string storageIds = 7;</code>
       * @return A list containing the storageIds.
       */
      public com.google.protobuf.ProtocolStringList
          getStorageIdsList() {
        storageIds_.makeImmutable();
        return storageIds_;
      }
      /**
       * <code>repeated string storageIds = 7;</code>
       * @return The count of storageIds.
       */
      public int getStorageIdsCount() {
        return storageIds_.size();
      }
      /**
       * <code>repeated string storageIds = 7;</code>
       * @param index The index of the element to return.
       * @return The storageIds at the given index.
       */
      public java.lang.String getStorageIds(int index) {
        return storageIds_.get(index);
      }
      /**
       * <code>repeated string storageIds = 7;</code>
       * @param index The index of the value to return.
       * @return The bytes of the storageIds at the given index.
       */
      public com.google.protobuf.ByteString
          getStorageIdsBytes(int index) {
        return storageIds_.getByteString(index);
      }
      /**
       * <code>repeated string storageIds = 7;</code>
       * @param index The index to set the value at.
       * @param value The storageIds to set.
       * @return This builder for chaining.
       */
      public Builder setStorageIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureStorageIdsIsMutable();
        storageIds_.set(index, value);
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string storageIds = 7;</code>
       * @param value The storageIds to add.
       * @return This builder for chaining.
       */
      public Builder addStorageIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureStorageIdsIsMutable();
        storageIds_.add(value);
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string storageIds = 7;</code>
       * @param values The storageIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllStorageIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureStorageIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, storageIds_);
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string storageIds = 7;</code>
       * @return This builder for chaining.
       */
      public Builder clearStorageIds() {
        storageIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000040);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string storageIds = 7;</code>
       * @param value The bytes of the storageIds to add.
       * @return This builder for chaining.
       */
      public Builder addStorageIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureStorageIdsIsMutable();
        storageIds_.add(value);
        bitField0_ |= 0x00000040;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList memoryIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureMemoryIdsIsMutable() {
        if (!memoryIds_.isModifiable()) {
          memoryIds_ = new com.google.protobuf.LazyStringArrayList(memoryIds_);
        }
        bitField0_ |= 0x00000080;
      }
      /**
       * <code>repeated string memoryIds = 8;</code>
       * @return A list containing the memoryIds.
       */
      public com.google.protobuf.ProtocolStringList
          getMemoryIdsList() {
        memoryIds_.makeImmutable();
        return memoryIds_;
      }
      /**
       * <code>repeated string memoryIds = 8;</code>
       * @return The count of memoryIds.
       */
      public int getMemoryIdsCount() {
        return memoryIds_.size();
      }
      /**
       * <code>repeated string memoryIds = 8;</code>
       * @param index The index of the element to return.
       * @return The memoryIds at the given index.
       */
      public java.lang.String getMemoryIds(int index) {
        return memoryIds_.get(index);
      }
      /**
       * <code>repeated string memoryIds = 8;</code>
       * @param index The index of the value to return.
       * @return The bytes of the memoryIds at the given index.
       */
      public com.google.protobuf.ByteString
          getMemoryIdsBytes(int index) {
        return memoryIds_.getByteString(index);
      }
      /**
       * <code>repeated string memoryIds = 8;</code>
       * @param index The index to set the value at.
       * @param value The memoryIds to set.
       * @return This builder for chaining.
       */
      public Builder setMemoryIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureMemoryIdsIsMutable();
        memoryIds_.set(index, value);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string memoryIds = 8;</code>
       * @param value The memoryIds to add.
       * @return This builder for chaining.
       */
      public Builder addMemoryIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureMemoryIdsIsMutable();
        memoryIds_.add(value);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string memoryIds = 8;</code>
       * @param values The memoryIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllMemoryIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureMemoryIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, memoryIds_);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string memoryIds = 8;</code>
       * @return This builder for chaining.
       */
      public Builder clearMemoryIds() {
        memoryIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000080);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string memoryIds = 8;</code>
       * @param value The bytes of the memoryIds to add.
       * @return This builder for chaining.
       */
      public Builder addMemoryIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureMemoryIdsIsMutable();
        memoryIds_.add(value);
        bitField0_ |= 0x00000080;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList videoCardIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensureVideoCardIdsIsMutable() {
        if (!videoCardIds_.isModifiable()) {
          videoCardIds_ = new com.google.protobuf.LazyStringArrayList(videoCardIds_);
        }
        bitField0_ |= 0x00000100;
      }
      /**
       * <code>repeated string videoCardIds = 9;</code>
       * @return A list containing the videoCardIds.
       */
      public com.google.protobuf.ProtocolStringList
          getVideoCardIdsList() {
        videoCardIds_.makeImmutable();
        return videoCardIds_;
      }
      /**
       * <code>repeated string videoCardIds = 9;</code>
       * @return The count of videoCardIds.
       */
      public int getVideoCardIdsCount() {
        return videoCardIds_.size();
      }
      /**
       * <code>repeated string videoCardIds = 9;</code>
       * @param index The index of the element to return.
       * @return The videoCardIds at the given index.
       */
      public java.lang.String getVideoCardIds(int index) {
        return videoCardIds_.get(index);
      }
      /**
       * <code>repeated string videoCardIds = 9;</code>
       * @param index The index of the value to return.
       * @return The bytes of the videoCardIds at the given index.
       */
      public com.google.protobuf.ByteString
          getVideoCardIdsBytes(int index) {
        return videoCardIds_.getByteString(index);
      }
      /**
       * <code>repeated string videoCardIds = 9;</code>
       * @param index The index to set the value at.
       * @param value The videoCardIds to set.
       * @return This builder for chaining.
       */
      public Builder setVideoCardIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureVideoCardIdsIsMutable();
        videoCardIds_.set(index, value);
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string videoCardIds = 9;</code>
       * @param value The videoCardIds to add.
       * @return This builder for chaining.
       */
      public Builder addVideoCardIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensureVideoCardIdsIsMutable();
        videoCardIds_.add(value);
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string videoCardIds = 9;</code>
       * @param values The videoCardIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllVideoCardIds(
          java.lang.Iterable<java.lang.String> values) {
        ensureVideoCardIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, videoCardIds_);
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string videoCardIds = 9;</code>
       * @return This builder for chaining.
       */
      public Builder clearVideoCardIds() {
        videoCardIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000100);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string videoCardIds = 9;</code>
       * @param value The bytes of the videoCardIds to add.
       * @return This builder for chaining.
       */
      public Builder addVideoCardIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensureVideoCardIdsIsMutable();
        videoCardIds_.add(value);
        bitField0_ |= 0x00000100;
        onChanged();
        return this;
      }

      private com.google.protobuf.LazyStringArrayList powerSupplyIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
      private void ensurePowerSupplyIdsIsMutable() {
        if (!powerSupplyIds_.isModifiable()) {
          powerSupplyIds_ = new com.google.protobuf.LazyStringArrayList(powerSupplyIds_);
        }
        bitField0_ |= 0x00000200;
      }
      /**
       * <code>repeated string powerSupplyIds = 10;</code>
       * @return A list containing the powerSupplyIds.
       */
      public com.google.protobuf.ProtocolStringList
          getPowerSupplyIdsList() {
        powerSupplyIds_.makeImmutable();
        return powerSupplyIds_;
      }
      /**
       * <code>repeated string powerSupplyIds = 10;</code>
       * @return The count of powerSupplyIds.
       */
      public int getPowerSupplyIdsCount() {
        return powerSupplyIds_.size();
      }
      /**
       * <code>repeated string powerSupplyIds = 10;</code>
       * @param index The index of the element to return.
       * @return The powerSupplyIds at the given index.
       */
      public java.lang.String getPowerSupplyIds(int index) {
        return powerSupplyIds_.get(index);
      }
      /**
       * <code>repeated string powerSupplyIds = 10;</code>
       * @param index The index of the value to return.
       * @return The bytes of the powerSupplyIds at the given index.
       */
      public com.google.protobuf.ByteString
          getPowerSupplyIdsBytes(int index) {
        return powerSupplyIds_.getByteString(index);
      }
      /**
       * <code>repeated string powerSupplyIds = 10;</code>
       * @param index The index to set the value at.
       * @param value The powerSupplyIds to set.
       * @return This builder for chaining.
       */
      public Builder setPowerSupplyIds(
          int index, java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePowerSupplyIdsIsMutable();
        powerSupplyIds_.set(index, value);
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string powerSupplyIds = 10;</code>
       * @param value The powerSupplyIds to add.
       * @return This builder for chaining.
       */
      public Builder addPowerSupplyIds(
          java.lang.String value) {
        if (value == null) { throw new NullPointerException(); }
        ensurePowerSupplyIdsIsMutable();
        powerSupplyIds_.add(value);
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string powerSupplyIds = 10;</code>
       * @param values The powerSupplyIds to add.
       * @return This builder for chaining.
       */
      public Builder addAllPowerSupplyIds(
          java.lang.Iterable<java.lang.String> values) {
        ensurePowerSupplyIdsIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, powerSupplyIds_);
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string powerSupplyIds = 10;</code>
       * @return This builder for chaining.
       */
      public Builder clearPowerSupplyIds() {
        powerSupplyIds_ =
          com.google.protobuf.LazyStringArrayList.emptyList();
        bitField0_ = (bitField0_ & ~0x00000200);;
        onChanged();
        return this;
      }
      /**
       * <code>repeated string powerSupplyIds = 10;</code>
       * @param value The bytes of the powerSupplyIds to add.
       * @return This builder for chaining.
       */
      public Builder addPowerSupplyIdsBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) { throw new NullPointerException(); }
        checkByteStringIsUtf8(value);
        ensurePowerSupplyIdsIsMutable();
        powerSupplyIds_.add(value);
        bitField0_ |= 0x00000200;
        onChanged();
        return this;
      }

      private long creationDate_ ;
      /**
       * <code>int64 creationDate = 11;</code>
       * @return The creationDate.
       */
      @java.lang.Override
      public long getCreationDate() {
        return creationDate_;
      }
      /**
       * <code>int64 creationDate = 11;</code>
       * @param value The creationDate to set.
       * @return This builder for chaining.
       */
      public Builder setCreationDate(long value) {

        creationDate_ = value;
        bitField0_ |= 0x00000400;
        onChanged();
        return this;
      }
      /**
       * <code>int64 creationDate = 11;</code>
       * @return This builder for chaining.
       */
      public Builder clearCreationDate() {
        bitField0_ = (bitField0_ & ~0x00000400);
        creationDate_ = 0L;
        onChanged();
        return this;
      }

      private long lastUpdateDate_ ;
      /**
       * <code>int64 lastUpdateDate = 12;</code>
       * @return The lastUpdateDate.
       */
      @java.lang.Override
      public long getLastUpdateDate() {
        return lastUpdateDate_;
      }
      /**
       * <code>int64 lastUpdateDate = 12;</code>
       * @param value The lastUpdateDate to set.
       * @return This builder for chaining.
       */
      public Builder setLastUpdateDate(long value) {

        lastUpdateDate_ = value;
        bitField0_ |= 0x00000800;
        onChanged();
        return this;
      }
      /**
       * <code>int64 lastUpdateDate = 12;</code>
       * @return This builder for chaining.
       */
      public Builder clearLastUpdateDate() {
        bitField0_ = (bitField0_ & ~0x00000800);
        lastUpdateDate_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:transfers.PcBuild)
    }

    // @@protoc_insertion_point(class_scope:transfers.PcBuild)
    private static final transfers.PcBuildOuterClass.PcBuild DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new transfers.PcBuildOuterClass.PcBuild();
    }

    public static transfers.PcBuildOuterClass.PcBuild getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<PcBuild>
        PARSER = new com.google.protobuf.AbstractParser<PcBuild>() {
      @java.lang.Override
      public PcBuild parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<PcBuild> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<PcBuild> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public transfers.PcBuildOuterClass.PcBuild getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_transfers_PcBuild_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_transfers_PcBuild_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030transfers/pc_build.proto\022\ttransfers\"\376\001" +
      "\n\007PcBuild\022\014\n\004uuid\030\001 \001(\t\022\023\n\013displayName\030\002" +
      " \001(\t\022\023\n\013description\030\003 \001(\t\022\020\n\010username\030\004 " +
      "\001(\t\022\016\n\006cpuIds\030\005 \003(\t\022\026\n\016motherboardIds\030\006 " +
      "\003(\t\022\022\n\nstorageIds\030\007 \003(\t\022\021\n\tmemoryIds\030\010 \003" +
      "(\t\022\024\n\014videoCardIds\030\t \003(\t\022\026\n\016powerSupplyI" +
      "ds\030\n \003(\t\022\024\n\014creationDate\030\013 \001(\003\022\026\n\016lastUp" +
      "dateDate\030\014 \001(\003b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_transfers_PcBuild_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_transfers_PcBuild_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_transfers_PcBuild_descriptor,
        new java.lang.String[] { "Uuid", "DisplayName", "Description", "Username", "CpuIds", "MotherboardIds", "StorageIds", "MemoryIds", "VideoCardIds", "PowerSupplyIds", "CreationDate", "LastUpdateDate", });
    descriptor.resolveAllFeaturesImmutable();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
