name: Deploy Docker Container

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      APP_NAME: pc_builder
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK and Maven
        run: |
          sudo apt-get update
          sudo apt-get install -y maven default-jdk
          mvn -v

      - name: Build app
        run: ./run build

      - name: Build Docker image
        run: |
          docker build -t ${APP_NAME}:latest .
          docker image prune -f

      - name: Remove old Docker container
        run: |
          docker stop ${APP_NAME} || true
          docker rm ${APP_NAME} || true

      - name: Run Docker container
        run: |
          docker run -d \
            --name ${APP_NAME} \
            --network stack_default \
            -p "8102:8080" \
            -e DB_URL=${{ secrets.DB_URL }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            ${APP_NAME}:latest

